os:
  - linux
  - osx

language: c

compiler:
    - clang

before_script:
    - curl -OL "https://github.com/stan-dev/cmdstan/releases/download/v2.16.0/cmdstan-2.16.0.tar.gz"
    - tar -xvzf cmdstan-2.16.0.tar.gz
    - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get update -qq ; fi
    - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get install -y build-essential ; fi

script:
    - STAN_ROOT=../cmdstan-2.16.0/ make all