build_script:
  - ps: Start-FileDownload "https://ci.appveyor.com/api/projects/ryanpdwyer/cmdstan/artifacts/cmdstan.zip" C:\cmdstan.zip; echo "Finished downloading cmdstan"
  # See http://stackoverflow.com/a/27771099
  - ps: Expand-Archive C:\cmdstan.zip -dest C:\
  - SET PATH=C:\msys64\usr\bin;C:\cmdstan\bin;%PATH%
  - g++ --version
  - cd C:\cmdstan
  - make -p
  - make /c/projects/stan-linear-ex/line.exe
  - make /c/projects/stan-linear-ex/transformed-line.exe
  - make /c/projects/stan-linear-ex/transformed-scaled-line.exe

artifacts:

  - path: '*.exe'